/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

import Ajustes.Estilos;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author terciodemarte
 */
public class Calculadora extends javax.swing.JFrame {

    //VARIABLES PARA ALMACENAR LOS VALORES;
    private double valor1 = 0, valor2 = 0, resultado = -1;
    private int operacion = -1;
    boolean control = false;
    /* equivalencia del valor de operaciones
        1 para suma
        2 para resta
        3 para multiplicacion
        4 para division
        5 para raiz cuadrada
     */
    private int maxCaracteres = 20;
    /**
     * Creates new form Calculadora2
     */
    public Calculadora() {
        initComponents();
       
    }
    
    @Override
    public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/calculadora.png"));
    return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        display = new javax.swing.JPanel();
        output = new javax.swing.JTextField();
        input = new javax.swing.JTextField();
        boton = new javax.swing.JPanel();
        b1 = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        b2 = new javax.swing.JPanel();
        t2 = new javax.swing.JLabel();
        b7 = new javax.swing.JPanel();
        t7 = new javax.swing.JLabel();
        b8 = new javax.swing.JPanel();
        t8 = new javax.swing.JLabel();
        b9 = new javax.swing.JPanel();
        t9 = new javax.swing.JLabel();
        suma = new javax.swing.JPanel();
        t10 = new javax.swing.JLabel();
        b3 = new javax.swing.JPanel();
        t3 = new javax.swing.JLabel();
        b4 = new javax.swing.JPanel();
        t4 = new javax.swing.JLabel();
        b5 = new javax.swing.JPanel();
        t5 = new javax.swing.JLabel();
        b6 = new javax.swing.JPanel();
        t6 = new javax.swing.JLabel();
        resta = new javax.swing.JPanel();
        t11 = new javax.swing.JLabel();
        multi = new javax.swing.JPanel();
        t12 = new javax.swing.JLabel();
        dividir = new javax.swing.JPanel();
        t13 = new javax.swing.JLabel();
        b0 = new javax.swing.JPanel();
        t0 = new javax.swing.JLabel();
        bc = new javax.swing.JPanel();
        tc = new javax.swing.JLabel();
        bc1 = new javax.swing.JPanel();
        tc1 = new javax.swing.JLabel();
        salir = new javax.swing.JPanel();
        tc2 = new javax.swing.JLabel();
        raiz = new javax.swing.JPanel();
        t14 = new javax.swing.JLabel();
        igual = new javax.swing.JPanel();
        t16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("calculadora");
        setIconImages(getIconImages());
        setLocation(new java.awt.Point(20, 20));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(Estilos.getColorPanelBlanco());

        display.setBackground(Estilos.getColorPanelBlanco());

        output.setBackground(Estilos.getColorPanelBlanco());
        output.setFont(Estilos.getFuenteCuerpo());
        output.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        output.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        output.setDisabledTextColor(Estilos.getColorFuenteCuerpo());
        output.setEnabled(false);

        input.setBackground(Estilos.getColorPanelBlanco());
        input.setFont(Estilos.getFuenteCuerpo());
        input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        input.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input.setDisabledTextColor(Estilos.getColorFuenteCuerpo());
        input.setEnabled(false);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(displayLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(displayLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        boton.setBackground(Estilos.getColorPanelBlanco());
        boton.setLayout(null);

        b1.setBackground(Estilos.getColorPanel());
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
        });

        t1.setFont(Estilos.getFuenteCuerpo());
        t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t1.setText("1");

        javax.swing.GroupLayout b1Layout = new javax.swing.GroupLayout(b1);
        b1.setLayout(b1Layout);
        b1Layout.setHorizontalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b1Layout.setVerticalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b1);
        b1.setBounds(10, 120, 50, 50);

        b2.setBackground(Estilos.getColorPanel());
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });

        t2.setFont(Estilos.getFuenteCuerpo());
        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("2");

        javax.swing.GroupLayout b2Layout = new javax.swing.GroupLayout(b2);
        b2.setLayout(b2Layout);
        b2Layout.setHorizontalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b2Layout.setVerticalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b2);
        b2.setBounds(70, 120, 50, 50);

        b7.setBackground(Estilos.getColorPanel());
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b7MouseExited(evt);
            }
        });

        t7.setFont(Estilos.getFuenteCuerpo());
        t7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t7.setText("7");

        javax.swing.GroupLayout b7Layout = new javax.swing.GroupLayout(b7);
        b7.setLayout(b7Layout);
        b7Layout.setHorizontalGroup(
            b7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b7Layout.setVerticalGroup(
            b7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b7);
        b7.setBounds(10, 0, 50, 50);

        b8.setBackground(Estilos.getColorPanel());
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b8MouseExited(evt);
            }
        });

        t8.setFont(Estilos.getFuenteCuerpo());
        t8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t8.setText("8");

        javax.swing.GroupLayout b8Layout = new javax.swing.GroupLayout(b8);
        b8.setLayout(b8Layout);
        b8Layout.setHorizontalGroup(
            b8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b8Layout.setVerticalGroup(
            b8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b8);
        b8.setBounds(70, 0, 50, 50);

        b9.setBackground(Estilos.getColorPanel());
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b9MouseExited(evt);
            }
        });

        t9.setFont(Estilos.getFuenteCuerpo());
        t9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t9.setText("9");

        javax.swing.GroupLayout b9Layout = new javax.swing.GroupLayout(b9);
        b9.setLayout(b9Layout);
        b9Layout.setHorizontalGroup(
            b9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b9Layout.setVerticalGroup(
            b9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b9);
        b9.setBounds(130, 0, 50, 50);

        suma.setBackground(Estilos.getColorPanel());
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sumaMouseExited(evt);
            }
        });

        t10.setFont(Estilos.getFuenteCuerpo());
        t10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t10.setText("+");

        javax.swing.GroupLayout sumaLayout = new javax.swing.GroupLayout(suma);
        suma.setLayout(sumaLayout);
        sumaLayout.setHorizontalGroup(
            sumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        sumaLayout.setVerticalGroup(
            sumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(suma);
        suma.setBounds(200, 0, 50, 50);

        b3.setBackground(Estilos.getColorPanel());
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
        });

        t3.setFont(Estilos.getFuenteCuerpo());
        t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t3.setText("3");

        javax.swing.GroupLayout b3Layout = new javax.swing.GroupLayout(b3);
        b3.setLayout(b3Layout);
        b3Layout.setHorizontalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b3Layout.setVerticalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b3);
        b3.setBounds(130, 120, 50, 50);

        b4.setBackground(Estilos.getColorPanel());
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
        });

        t4.setFont(Estilos.getFuenteCuerpo());
        t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t4.setText("4");

        javax.swing.GroupLayout b4Layout = new javax.swing.GroupLayout(b4);
        b4.setLayout(b4Layout);
        b4Layout.setHorizontalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b4Layout.setVerticalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b4);
        b4.setBounds(10, 60, 50, 50);

        b5.setBackground(Estilos.getColorPanel());
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });

        t5.setFont(Estilos.getFuenteCuerpo());
        t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t5.setText("5");

        javax.swing.GroupLayout b5Layout = new javax.swing.GroupLayout(b5);
        b5.setLayout(b5Layout);
        b5Layout.setHorizontalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b5Layout.setVerticalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b5);
        b5.setBounds(70, 60, 50, 50);

        b6.setBackground(Estilos.getColorPanel());
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6MouseExited(evt);
            }
        });

        t6.setFont(Estilos.getFuenteCuerpo());
        t6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t6.setText("6");

        javax.swing.GroupLayout b6Layout = new javax.swing.GroupLayout(b6);
        b6.setLayout(b6Layout);
        b6Layout.setHorizontalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b6Layout.setVerticalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b6);
        b6.setBounds(130, 60, 50, 50);

        resta.setBackground(Estilos.getColorPanel());
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaMouseExited(evt);
            }
        });

        t11.setFont(Estilos.getFuenteCuerpo());
        t11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t11.setText("-");

        javax.swing.GroupLayout restaLayout = new javax.swing.GroupLayout(resta);
        resta.setLayout(restaLayout);
        restaLayout.setHorizontalGroup(
            restaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        restaLayout.setVerticalGroup(
            restaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(resta);
        resta.setBounds(200, 60, 50, 50);

        multi.setBackground(Estilos.getColorPanel());
        multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiMouseExited(evt);
            }
        });

        t12.setFont(Estilos.getFuenteCuerpo());
        t12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t12.setText("*");

        javax.swing.GroupLayout multiLayout = new javax.swing.GroupLayout(multi);
        multi.setLayout(multiLayout);
        multiLayout.setHorizontalGroup(
            multiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        multiLayout.setVerticalGroup(
            multiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(multi);
        multi.setBounds(200, 120, 50, 50);

        dividir.setBackground(Estilos.getColorPanel());
        dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dividirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dividirMouseExited(evt);
            }
        });

        t13.setFont(Estilos.getFuenteCuerpo());
        t13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t13.setText("/");

        javax.swing.GroupLayout dividirLayout = new javax.swing.GroupLayout(dividir);
        dividir.setLayout(dividirLayout);
        dividirLayout.setHorizontalGroup(
            dividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        dividirLayout.setVerticalGroup(
            dividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(dividir);
        dividir.setBounds(200, 180, 50, 50);

        b0.setBackground(Estilos.getColorPanel());
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b0MouseExited(evt);
            }
        });

        t0.setFont(Estilos.getFuenteCuerpo());
        t0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t0.setText("0");

        javax.swing.GroupLayout b0Layout = new javax.swing.GroupLayout(b0);
        b0.setLayout(b0Layout);
        b0Layout.setHorizontalGroup(
            b0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t0, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        b0Layout.setVerticalGroup(
            b0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t0, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(b0);
        b0.setBounds(70, 180, 50, 50);

        bc.setBackground(Estilos.getColorPanel());
        bc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcMouseExited(evt);
            }
        });

        tc.setFont(Estilos.getFuenteCuerpo());
        tc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tc.setText(",");

        javax.swing.GroupLayout bcLayout = new javax.swing.GroupLayout(bc);
        bc.setLayout(bcLayout);
        bcLayout.setHorizontalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        bcLayout.setVerticalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(bc);
        bc.setBounds(130, 180, 50, 50);

        bc1.setBackground(Estilos.getColorPanel());
        bc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bc1MouseExited(evt);
            }
        });

        tc1.setFont(Estilos.getFuenteCuerpo());
        tc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tc1.setText("C");

        javax.swing.GroupLayout bc1Layout = new javax.swing.GroupLayout(bc1);
        bc1.setLayout(bc1Layout);
        bc1Layout.setHorizontalGroup(
            bc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        bc1Layout.setVerticalGroup(
            bc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(bc1);
        bc1.setBounds(10, 180, 50, 50);

        salir.setBackground(Estilos.getColorPanel());
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        tc2.setFont(Estilos.getFuenteCuerpo());
        tc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tc2.setText("SALIR");

        javax.swing.GroupLayout salirLayout = new javax.swing.GroupLayout(salir);
        salir.setLayout(salirLayout);
        salirLayout.setHorizontalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        salirLayout.setVerticalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tc2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(salir);
        salir.setBounds(80, 240, 150, 50);

        raiz.setBackground(Estilos.getColorPanel());
        raiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raizMouseExited(evt);
            }
        });

        t14.setFont(Estilos.getFuenteCuerpo());
        t14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t14.setText("√");

        javax.swing.GroupLayout raizLayout = new javax.swing.GroupLayout(raiz);
        raiz.setLayout(raizLayout);
        raizLayout.setHorizontalGroup(
            raizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        raizLayout.setVerticalGroup(
            raizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(raiz);
        raiz.setBounds(260, 0, 50, 50);

        igual.setBackground(Estilos.getColorSobreBoton());
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                igualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                igualMouseExited(evt);
            }
        });

        t16.setBackground(Estilos.getColorSobreBoton());
        t16.setFont(Estilos.getFuenteCuerpo());
        t16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t16.setText("=");

        javax.swing.GroupLayout igualLayout = new javax.swing.GroupLayout(igual);
        igual.setLayout(igualLayout);
        igualLayout.setHorizontalGroup(
            igualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        igualLayout.setVerticalGroup(
            igualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        boton.add(igual);
        igual.setBounds(260, 180, 50, 50);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void b7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseEntered
        b7.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b7MouseEntered

    private void b7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseExited
        b7.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b7MouseExited

    private void b8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseEntered
        b8.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b8MouseEntered

    private void b8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseExited
        b8.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b8MouseExited

    private void b9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseEntered
        b9.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b9MouseEntered

    private void b9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseExited
        b9.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b9MouseExited

    private void sumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseEntered
        suma.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_sumaMouseEntered

    private void sumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseExited
        suma.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_sumaMouseExited

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
       b1.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        b1.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
       b2.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        b2.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        b3.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b3MouseEntered

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        b3.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b3MouseExited

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        b4.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        b4.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b4MouseExited

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        b5.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        b5.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b5MouseExited

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
        b6.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b6MouseEntered

    private void b6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseExited
        b6.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b6MouseExited

    private void restaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseEntered
       resta.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_restaMouseEntered

    private void restaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseExited
        resta.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_restaMouseExited

    private void multiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiMouseEntered
        multi.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_multiMouseEntered

    private void multiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiMouseExited
        multi.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_multiMouseExited

    private void dividirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividirMouseEntered
       dividir.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_dividirMouseEntered

    private void dividirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividirMouseExited
        dividir.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_dividirMouseExited

    private void b0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseEntered
        b0.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_b0MouseEntered

    private void b0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseExited
        b0.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_b0MouseExited

    private void bcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcMouseEntered
       bc.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_bcMouseEntered

    private void bcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcMouseExited
        bc.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_bcMouseExited

    private void bc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bc1MouseEntered
        bc1.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_bc1MouseEntered

    private void bc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bc1MouseExited
        bc1.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_bc1MouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
       salir.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_salirMouseExited

    private void raizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizMouseEntered
        raiz.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_raizMouseEntered

    private void raizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizMouseExited
       raiz.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_raizMouseExited

    private void igualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseEntered
        igual.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_igualMouseEntered

    private void igualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseExited
        igual.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_igualMouseExited

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
          // TODO add your handling code here:
        limpiarError();
        capturarValorInput();
        operacion = 1;
        output.setText(valor1 + " +");
    }//GEN-LAST:event_sumaMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        // TODO add your handling code here:
        limpiarError();
        capturarValorInput();
        operacion = 2;
        output.setText(valor1 + " -");
        /*
        try {
            if (!input.getText().isEmpty() && output.getText().isEmpty()) { // si el input tiene valor y el output no tiene nada sube el valor y coloca el simbolo
                valor1 = Double.parseDouble(input.getText());
                output.setText(valor1 + " -");
                input.setText("0");
                operacion = 2;
            } else if (!input.getText().isEmpty() && !output.getText().isEmpty()) { //si el input tiene valor y el output ya tiene valor realiza la operacion y limpia el input
                valor2 = Double.parseDouble(input.getText());
                operaciones();
                output.setText(resultado + " -");
                input.setText("0");
                operacion = 2;
            } else if (input.getText().isEmpty() && !output.getText().isEmpty()) { //si el input esta vacio y el output ya tiene valor cambia la operacion
                output.setText(valor1 + " -");
                operacion = 2;
            }
        } catch (NumberFormatException e) {
            output.setText("ERROR");
        }
        */
    }//GEN-LAST:event_restaMouseClicked

    private void multiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiMouseClicked
         // TODO add your handling code here:
        limpiarError();
        capturarValorInput();
        operacion = 3;
        output.setText(valor1 + " *");
    }//GEN-LAST:event_multiMouseClicked

    private void dividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividirMouseClicked
         // TODO add your handling code here:
        limpiarError();
        capturarValorInput();
        operacion = 4;
        output.setText(valor1 + " /");
    }//GEN-LAST:event_dividirMouseClicked

    private void bc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bc1MouseClicked
        // TODO add your handling code here:
        input.setText("0");
        output.setText("");
        valor1 = 0;
        valor2 = 0;
        resultado = -1;
        operacion = -1;
    }//GEN-LAST:event_bc1MouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void raizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizMouseClicked
       // TODO add your handling code here:
        limpiarError();
        capturarValorInput();
        operacion =5;
        operaciones();
        output.setText("√"+valor1 + "");
    }//GEN-LAST:event_raizMouseClicked

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "1");
        }
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
         // TODO add your handling code here:
        limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "2");
        }
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "3");
        }
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "4");
        }
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "5");
        }
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "6");
        }
    }//GEN-LAST:event_b6MouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "7");
        }
    }//GEN-LAST:event_b7MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "8");
        }
    }//GEN-LAST:event_b8MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "9");
        }
    }//GEN-LAST:event_b9MouseClicked

    private void b0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseClicked
        // TODO add your handling code here:
         limpiarError();
        limparCerosIzquierda();
        if (input.getText().length() < maxCaracteres) {
            input.setText(input.getText() + "0");
        }
    }//GEN-LAST:event_b0MouseClicked

    private void bcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcMouseClicked
        // TODO add your handling code here:
         limpiarError();
        if (input.getText().length() < maxCaracteres) {
            if (input.getText().length() == 0) {
                input.setText("0.");
            } else if (!input.getText().contains(".")) {
                input.setText(input.getText() + ".");
            }
        }
    }//GEN-LAST:event_bcMouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
        // TODO add your handling code here:
          if (operacion != -1) {
            try {
                if (!input.getText().isEmpty()&& !input.getText().equalsIgnoreCase("0")) {
                    valor2 = Double.parseDouble(input.getText());
                }
                operaciones();
                if (control) {
                    output.setText(resultado + "");
                    input.setText("0");
                    control = true;
                }
            } catch (NumberFormatException e) {
                input.setText("ERROR");
            }
            
        } 
    }//GEN-LAST:event_igualMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER){
            //No puedo llamar a los metodos de arriba
        }
    }//GEN-LAST:event_formKeyPressed

    private void operaciones() {
        switch (operacion) {
            case 1://suma                
                resultado = valor1 + valor2;
                valor1 = resultado;
                control = true;
                break;
            case 2://resta
                resultado = valor1 - valor2;
                valor1 = resultado;
                control = true;
                break;
            case 3://multiplicacion
                resultado = valor1 * valor2;
                valor1 = resultado;
                control = true;
                break;
            case 4://division
                if (valor2 != 0) {
                    resultado = valor1 / valor2;
                    valor1 = resultado;
                    control = true;
                } else {
                    valor1 = 0;
                    valor2 = 0;
                    resultado = 0;
                    operacion = -1;
                    output.setText("No puedes div entre 0");
                    input.setText("ERROR");
                    control = false;
                }
                break;
            case 5://RaizCuadrada
                if (valor1 >0) {
                    resultado = Math.sqrt(valor1);
                    valor1 = resultado;
                } else {
                    output.setText("No puedes ser < 0");
                    input.setText("ERROR");
                }
                break;
            default:
                break;
        }
    }
    
    // metodo para capturar el valor del input
    public void capturarValorInput(){
        try {
            if (!input.getText().isEmpty() && !input.getText().equalsIgnoreCase("ERROR") && output.getText().isEmpty()) { // si el input tiene valor y el output no tiene nada sube el valor y coloca el simbolo
                valor1 = Double.parseDouble(input.getText());
                input.setText("0");
            }
        } catch (NumberFormatException e) {
            output.setText("ERROR");
        }
    }
    
     //metodo para limpiar si tiene un error.
    public void limpiarError(){
        if (input.getText().equalsIgnoreCase("ERROR")){// si tiene un error limpia para volver a colocar numeros ;)
            input.setText("0");
            output.setText("");
        }
    }
    
     //metodo para quitar ceros a la izquierda
    public void limparCerosIzquierda (){
        if (input.getText().equalsIgnoreCase("0")) {
            input.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel b0;
    private javax.swing.JPanel b1;
    private javax.swing.JPanel b2;
    private javax.swing.JPanel b3;
    private javax.swing.JPanel b4;
    private javax.swing.JPanel b5;
    private javax.swing.JPanel b6;
    private javax.swing.JPanel b7;
    private javax.swing.JPanel b8;
    private javax.swing.JPanel b9;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bc;
    private javax.swing.JPanel bc1;
    private javax.swing.JPanel boton;
    private javax.swing.JPanel display;
    private javax.swing.JPanel dividir;
    private javax.swing.JPanel igual;
    private javax.swing.JTextField input;
    private javax.swing.JPanel multi;
    private javax.swing.JTextField output;
    private javax.swing.JPanel raiz;
    private javax.swing.JPanel resta;
    private javax.swing.JPanel salir;
    private javax.swing.JPanel suma;
    private javax.swing.JLabel t0;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JLabel tc;
    private javax.swing.JLabel tc1;
    private javax.swing.JLabel tc2;
    // End of variables declaration//GEN-END:variables
}
