package Ajustes;

import Main.Main;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

//REVISAR
//http://dar10comyr.blogspot.com/2015/06/tips-como-reproducir-sonidos-en-java.html
public class Ajustes extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Ajustes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        sonido = new javax.swing.JLabel();
        aplicar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        tamano = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();
        selectidioma = new javax.swing.JComboBox<>();
        No = new javax.swing.JRadioButton();
        Si = new javax.swing.JRadioButton();
        texto = new javax.swing.JSlider();
        valortexto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 720));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1070, 720));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sonido.setFont(Estilos.getFuenteCuerpo());
        sonido.setText("SONIDO");
        sonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sonidoMouseEntered(evt);
            }
        });
        background.add(sonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        aplicar.setBackground(Estilos.getColorPanel());
        aplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aplicarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLICAR");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout aplicarLayout = new javax.swing.GroupLayout(aplicar);
        aplicar.setLayout(aplicarLayout);
        aplicarLayout.setHorizontalGroup(
            aplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplicarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        aplicarLayout.setVerticalGroup(
            aplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 130, -1));

        titulo.setFont(Estilos.getFuenteCuerpo());
        titulo.setText("AJUSTES");
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tituloMouseEntered(evt);
            }
        });
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 49, -1, -1));

        tamano.setFont(Estilos.getFuenteCuerpo());
        tamano.setText("TAMAÑO TEXTO");
        tamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tamanoMouseEntered(evt);
            }
        });
        background.add(tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        idioma.setFont(Estilos.getFuenteCuerpo());
        idioma.setText("IDIOMA");
        idioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idiomaMouseEntered(evt);
            }
        });
        background.add(idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        selectidioma.setFont(Estilos.getFuenteCuerpo());
        selectidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        selectidioma.setBorder(null);
        background.add(selectidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        buttonGroup1.add(No);
        No.setFont(Estilos.getFuenteCuerpo());
        No.setText("NO");
        No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoMouseEntered(evt);
            }
        });
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        background.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        buttonGroup1.add(Si);
        Si.setFont(Estilos.getFuenteCuerpo());
        Si.setText("SI");
        Si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SiMouseEntered(evt);
            }
        });
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        background.add(Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        texto.setFont(Estilos.getFuenteCuerpo());
        texto.setMaximum(3);
        texto.setMinimum(1);
        texto.setValue(2);
        texto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textoStateChanged(evt);
            }
        });
        background.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, -1));

        valortexto.setFont(Estilos.getFuenteCuerpo());
        valortexto.setText("2");
        background.add(valortexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicarMouseEntered
        aplicar.setBackground(new Color(69, 212, 252));
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/aplicar.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_aplicarMouseEntered

    private void aplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicarMouseExited
        aplicar.setBackground(new Color(0, 155, 155));
    }//GEN-LAST:event_aplicarMouseExited

    private void aplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicarMouseClicked
        Configuracion.setTamano((byte)texto.getValue());
        switch (Configuracion.getTamano()) {
            case 1:
                Estilos.setSizeCuerpo(12);
                
                break;
            case 2:
                Estilos.setSizeCuerpo(18);
              
                break;
            case 3:
                Estilos.setSizeCuerpo(24);
             
                break;
        }
        
        Configuracion.setIdioma(selectidioma.getSelectedItem().toString());
        if (Si.isSelected()) {
            Configuracion.setSonido(true);

        } else {
            Configuracion.setSonido(false);
        }
        
        Ajustes a1 = new Ajustes();
        a1.setSize(1070,720);
        a1.setLocation(0, 0);
        Main.getCuerpo().removeAll();
        Main.getCuerpo().add(a1);
        Main.getCuerpo().revalidate();
        Main.getCuerpo().repaint();

    }//GEN-LAST:event_aplicarMouseClicked

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiActionPerformed

    private void textoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textoStateChanged
        valortexto.setText(Integer.toString(texto.getValue()));
    }//GEN-LAST:event_textoStateChanged

    private void tituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/ajustes.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tituloMouseEntered

    private void tamanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanoMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/tamaño_texto.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tamanoMouseEntered

    private void idiomaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/idioma.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_idiomaMouseEntered

    private void sonidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonidoMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/sonido.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sonidoMouseEntered

    private void SiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/si.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SiMouseEntered

    private void NoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseEntered
        if (Configuracion.isSonido()) {
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Audios/no.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }catch(FileNotFoundException ex){
                 Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Ajustes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_NoMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton Si;
    private javax.swing.JPanel aplicar;
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> selectidioma;
    private javax.swing.JLabel sonido;
    private javax.swing.JLabel tamano;
    private javax.swing.JSlider texto;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valortexto;
    // End of variables declaration//GEN-END:variables
}
