/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tablas;

import BBDD.ObjetoAlumnoBBDD;
import BBDD.MetodosAlumnoBBDD;
import Ajustes.Estilos;
import Main.Main;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author terciodemarte
 */
public class alumnos extends javax.swing.JPanel {

    /**
     * Creates new form alumnos
     */
    public alumnos() {
        initComponents();
        jTable1.getTableHeader().setOpaque(false);
        //NO RULA
        
        //jTable1.getTableHeader().setBackground(Estilos.getColorPanel());
        //jTable1.getTableHeader().setForeground(Estilos.getColorFuentePanel());
        
        DefaultTableModel modelC = (DefaultTableModel) jTable1.getModel();
        
        modelC.setRowCount(0);
        Object[] row = new Object[9];

        
        ArrayList<ObjetoAlumnoBBDD> lista = MetodosAlumnoBBDD.selectAlumnos(Main.getCon(), "%", "%", "%", "%", "%", "%", "%", "%") ;
        for (int i = 0; i < lista.size(); i++) {
            row[0] = lista.get(i).getUsuario();
            row[1] = lista.get(i).getAlias();
            row[2] = lista.get(i).getNombre();
            row[3] = lista.get(i).getApellido1();
            row[4] = lista.get(i).getApellido2();
            row[5] = lista.get(i).getDni();
            row[6] = lista.get(i).getEmail();
            row[7] = lista.get(i).getCurso();
            row[8] = lista.get(i).getFecha();
            modelC.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        datos = new javax.swing.JPanel();
        Apellido1 = new javax.swing.JPanel();
        ap1 = new javax.swing.JLabel();
        TFApellido1 = new javax.swing.JTextField();
        SepUsuario3 = new javax.swing.JSeparator();
        Alias = new javax.swing.JPanel();
        al = new javax.swing.JLabel();
        TFAlias = new javax.swing.JTextField();
        SepUsuario1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JPanel();
        us = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        SepUsuario = new javax.swing.JSeparator();
        curso = new javax.swing.JPanel();
        cu = new javax.swing.JLabel();
        TFCurso = new javax.swing.JTextField();
        SepUsuario7 = new javax.swing.JSeparator();
        DNI = new javax.swing.JPanel();
        dni = new javax.swing.JLabel();
        TFDni = new javax.swing.JTextField();
        SepUsuario5 = new javax.swing.JSeparator();
        Apellido2 = new javax.swing.JPanel();
        ap2 = new javax.swing.JLabel();
        TFApellido2 = new javax.swing.JTextField();
        SepUsuario4 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JPanel();
        no = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        SepUsuario2 = new javax.swing.JSeparator();
        email = new javax.swing.JPanel();
        em = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        SepUsuario6 = new javax.swing.JSeparator();
        buscar = new javax.swing.JPanel();
        buscartxt = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(Estilos.getColorPanelBlanco());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Alias", "Nombre", "1º Apellido", "2º Apellido ", "DNI", "Email", "Curso", "Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(Estilos.getColorSobreBoton());
        jTable1.setSelectionForeground(Estilos.getColorFuentePanel());
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        datos.setBackground(Estilos.getColorPanelBlanco());
        datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Apellido1.setBackground(new java.awt.Color(255, 255, 255));

        ap1.setFont(Estilos.getFuenteCuerpo());
        ap1.setText("Apellido 1");

        TFApellido1.setFont(Estilos.getFuenteCuerpo());
        TFApellido1.setForeground(new java.awt.Color(204, 204, 204));
        TFApellido1.setText("Inserte Apellido 1");
        TFApellido1.setBorder(null);
        TFApellido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFApellido1MousePressed(evt);
            }
        });
        TFApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFApellido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Apellido1Layout = new javax.swing.GroupLayout(Apellido1);
        Apellido1.setLayout(Apellido1Layout);
        Apellido1Layout.setHorizontalGroup(
            Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFApellido1)
                    .addGroup(Apellido1Layout.createSequentialGroup()
                        .addGroup(Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Apellido1Layout.setVerticalGroup(
            Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 344, -1));

        Alias.setBackground(new java.awt.Color(255, 255, 255));

        al.setFont(Estilos.getFuenteCuerpo());
        al.setText("Alias");

        TFAlias.setFont(Estilos.getFuenteCuerpo());
        TFAlias.setForeground(new java.awt.Color(204, 204, 204));
        TFAlias.setText("Inserte Alias");
        TFAlias.setBorder(null);
        TFAlias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFAliasMousePressed(evt);
            }
        });
        TFAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAliasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AliasLayout = new javax.swing.GroupLayout(Alias);
        Alias.setLayout(AliasLayout);
        AliasLayout.setHorizontalGroup(
            AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AliasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFAlias)
                    .addGroup(AliasLayout.createSequentialGroup()
                        .addGroup(AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AliasLayout.setVerticalGroup(
            AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AliasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(al)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(Alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 0, 348, -1));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));

        us.setFont(Estilos.getFuenteCuerpo());
        us.setText("Usuario");

        TFUsuario.setFont(Estilos.getFuenteCuerpo());
        TFUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TFUsuario.setText("Inserte nombre de usuario");
        TFUsuario.setBorder(null);
        TFUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFUsuarioMousePressed(evt);
            }
        });
        TFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFUsuario)
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(us)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        curso.setBackground(new java.awt.Color(255, 255, 255));

        cu.setFont(Estilos.getFuenteCuerpo());
        cu.setText("Curso");

        TFCurso.setFont(Estilos.getFuenteCuerpo());
        TFCurso.setForeground(new java.awt.Color(204, 204, 204));
        TFCurso.setText("Inserte Curso");
        TFCurso.setBorder(null);
        TFCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFCursoMousePressed(evt);
            }
        });
        TFCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cursoLayout = new javax.swing.GroupLayout(curso);
        curso.setLayout(cursoLayout);
        cursoLayout.setHorizontalGroup(
            cursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFCurso)
                    .addGroup(cursoLayout.createSequentialGroup()
                        .addGroup(cursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cursoLayout.setVerticalGroup(
            cursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 152, -1, -1));

        DNI.setBackground(new java.awt.Color(255, 255, 255));

        dni.setFont(Estilos.getFuenteCuerpo());
        dni.setText("DNI");

        TFDni.setFont(Estilos.getFuenteCuerpo());
        TFDni.setForeground(new java.awt.Color(204, 204, 204));
        TFDni.setText("Inserte DNI");
        TFDni.setBorder(null);
        TFDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFDniMousePressed(evt);
            }
        });
        TFDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DNILayout = new javax.swing.GroupLayout(DNI);
        DNI.setLayout(DNILayout);
        DNILayout.setHorizontalGroup(
            DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DNILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFDni)
                    .addGroup(DNILayout.createSequentialGroup()
                        .addGroup(DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DNILayout.setVerticalGroup(
            DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DNILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 76, -1, -1));

        Apellido2.setBackground(new java.awt.Color(255, 255, 255));

        ap2.setFont(Estilos.getFuenteCuerpo());
        ap2.setText("Apellido 2");

        TFApellido2.setFont(Estilos.getFuenteCuerpo());
        TFApellido2.setForeground(new java.awt.Color(204, 204, 204));
        TFApellido2.setText("Inserte Apellido 2");
        TFApellido2.setBorder(null);
        TFApellido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFApellido2MousePressed(evt);
            }
        });
        TFApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFApellido2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Apellido2Layout = new javax.swing.GroupLayout(Apellido2);
        Apellido2.setLayout(Apellido2Layout);
        Apellido2Layout.setHorizontalGroup(
            Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFApellido2)
                    .addGroup(Apellido2Layout.createSequentialGroup()
                        .addGroup(Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Apellido2Layout.setVerticalGroup(
            Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ap2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 76, 348, -1));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));

        no.setFont(Estilos.getFuenteCuerpo());
        no.setText("Nombre");

        TFNombre.setFont(Estilos.getFuenteCuerpo());
        TFNombre.setForeground(new java.awt.Color(204, 204, 204));
        TFNombre.setText("Inserte Nombre");
        TFNombre.setBorder(null);
        TFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFNombreMousePressed(evt);
            }
        });
        TFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreLayout = new javax.swing.GroupLayout(Nombre);
        Nombre.setLayout(NombreLayout);
        NombreLayout.setHorizontalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNombre)
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NombreLayout.setVerticalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(no)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 330, -1));

        email.setBackground(new java.awt.Color(255, 255, 255));

        em.setFont(Estilos.getFuenteCuerpo());
        em.setText("Email");

        TFEmail.setFont(Estilos.getFuenteCuerpo());
        TFEmail.setForeground(new java.awt.Color(204, 204, 204));
        TFEmail.setText("Inserte Email");
        TFEmail.setBorder(null);
        TFEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFEmailMousePressed(evt);
            }
        });
        TFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailLayout = new javax.swing.GroupLayout(email);
        email.setLayout(emailLayout);
        emailLayout.setHorizontalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFEmail)
                    .addGroup(emailLayout.createSequentialGroup()
                        .addGroup(emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SepUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        emailLayout.setVerticalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(em)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SepUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datos.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, 344, -1));

        buscar.setBackground(new java.awt.Color(0, 155, 155));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarMouseExited(evt);
            }
        });

        buscartxt.setFont(Estilos.getFuentePanel());
        buscartxt.setForeground(new java.awt.Color(255, 255, 255));
        buscartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscartxt.setText("Buscar");
        buscartxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        datos.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 210, -1));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TFUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUsuarioMousePressed
        if (TFUsuario.getText().equals("Inserte nombre de usuario")) {
            TFUsuario.setText("");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }

    }//GEN-LAST:event_TFUsuarioMousePressed

    private void TFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUsuarioActionPerformed

    private void TFAliasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFAliasMousePressed
        // TODO add your handling code here:
        if (TFAlias.getText().equals("Inserte Alias")) {
            TFAlias.setText("");
            TFAlias.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFAliasMousePressed

    private void TFAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAliasActionPerformed

    private void TFNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNombreMousePressed
        // TODO add your handling code here:
        if (TFNombre.getText().equals("Inserte Nombre")) {
            TFNombre.setText("");
            TFNombre.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFNombreMousePressed

    private void TFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombreActionPerformed

    private void TFApellido1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFApellido1MousePressed
        // TODO add your handling code here:
        if (TFApellido1.getText().equals("Inserte Apellido 1")) {
            TFApellido1.setText("");
            TFApellido1.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("nserte nombre de usuario");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFApellido1MousePressed

    private void TFApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFApellido1ActionPerformed

    private void TFApellido2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFApellido2MousePressed
        // TODO add your handling code here:
        if (TFApellido2.getText().equals("Inserte Apellido 2")) {
            TFApellido2.setText("");
            TFApellido2.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFApellido2MousePressed

    private void TFApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFApellido2ActionPerformed

    private void TFDniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDniMousePressed
        // TODO add your handling code here:
        if (TFDni.getText().equals("Inserte DNI")) {
            TFDni.setText("");
            TFDni.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFDniMousePressed

    private void TFDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDniActionPerformed

    private void TFEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFEmailMousePressed
        // TODO add your handling code here:
        if (TFEmail.getText().equals("Inserte Email")) {
            TFEmail.setText("");
            TFEmail.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte Curso");
        }
    }//GEN-LAST:event_TFEmailMousePressed

    private void TFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmailActionPerformed

    private void TFCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFCursoMousePressed
        // TODO add your handling code here:
        if (TFCurso.getText().equals("Inserte Curso")) {
            TFCurso.setText("");
            TFCurso.setForeground(Color.gray);
        }
        if (TFAlias.getText().isEmpty()) {
            TFAlias.setText("Inserte Alias");
        }
        if (TFNombre.getText().isEmpty()) {
            TFNombre.setText("Inserte Nombre");
        }
        if (TFApellido1.getText().isEmpty()) {
            TFApellido1.setText("Inserte Apellido 1");
        }
        if (TFApellido2.getText().isEmpty()) {
            TFApellido2.setText("Inserte Apellido 2");
        }
        if (TFDni.getText().isEmpty()) {
            TFDni.setText("Inserte DNI");
        }
        if (TFEmail.getText().isEmpty()) {
            TFEmail.setText("Inserte Email");
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte nombre de usuario");
        }
    }//GEN-LAST:event_TFCursoMousePressed

    private void TFCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCursoActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        actualizar();
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseEntered
        buscar.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseExited
        buscar.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_buscarMouseExited

    /**
     * Metodo para actualizar la tabla
     */
    private void actualizar() {
        ObjetoAlumnoBBDD objeto=buscador();
        
        DefaultTableModel modelC = (DefaultTableModel) jTable1.getModel();
        modelC.setRowCount(0);
        Object[] row = new Object[9];

        
        ArrayList<ObjetoAlumnoBBDD> lista = MetodosAlumnoBBDD.selectAlumnos(Main.getCon(), objeto.getUsuario(), objeto.getAlias(), objeto.getNombre(), objeto.getApellido1(), objeto.getApellido2(), objeto.getDni(), objeto.getEmail(), objeto.getCurso()) ;
        for (int i = 0; i < lista.size(); i++) {
            row[0] = lista.get(i).getUsuario();
            row[1] = lista.get(i).getAlias();
            row[2] = lista.get(i).getNombre();
            row[3] = lista.get(i).getApellido1();
            row[4] = lista.get(i).getApellido2();
            row[5] = lista.get(i).getDni();
            row[6] = lista.get(i).getEmail();
            row[7] = lista.get(i).getCurso();
            row[8] = lista.get(i).getFecha();
            modelC.addRow(row);
        }
    }
    /**
     * Metodo para coger los parametros de la busqueda
     * @return Objeto de la clase MetodosAlumnoBBDD para almacenar todos los parametros de la busqueda
     */
    private ObjetoAlumnoBBDD buscador(){
        ObjetoAlumnoBBDD objeto = new ObjetoAlumnoBBDD();
        if (TFUsuario.getText().equals("Inserte nombre de usuario") || TFUsuario.getText().isEmpty()) {
            objeto.setUsuario("%");
        } else {
            objeto.setUsuario("%"+TFUsuario.getText()+"%");
        }

        if (TFAlias.getText().equals("Inserte Alias") || TFAlias.getText().isEmpty()) {
            objeto.setAlias("%");
        } else {
            objeto.setAlias("%"+TFAlias.getText()+"%");
        }
        
        if (TFNombre.getText().equals("Inserte Nombre")|| TFNombre.getText().isEmpty()) {
            objeto.setNombre("%");
        } else {
            objeto.setNombre("%"+TFNombre.getText()+"%");
        }
        
        if (TFApellido1.getText().equals("Inserte Apellido 1") || TFApellido1.getText().isEmpty()) {
            objeto.setApellido1("%");
        } else {
            objeto.setApellido1("%"+TFApellido1.getText()+"%");
        }
        
        if (TFApellido2.getText().equals("Inserte Apellido 2") || TFApellido2.getText().isEmpty()) {
            objeto.setApellido2("%");
        }else {
            objeto.setApellido2("%"+TFApellido2.getText()+"%");
        }
        
        if (TFDni.getText().equals("Inserte DNI") || TFDni.getText().isEmpty()) {
            objeto.setDni("%");
        }else {
            objeto.setDni("%"+TFDni.getText()+"%");
        }
        
        if (TFEmail.getText().equals("Inserte Email") || TFEmail.getText().isEmpty()) {
            objeto.setEmail("%");
        }else {
            objeto.setEmail("%"+TFEmail.getText()+"%");
        }
        if (TFCurso.getText().equals("Inserte Curso") || TFCurso.getText().isEmpty()) {
            objeto.setCurso("%");
        }else {
            objeto.setCurso("%"+TFCurso.getText()+"%");
        }
        return objeto;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alias;
    private javax.swing.JPanel Apellido1;
    private javax.swing.JPanel Apellido2;
    private javax.swing.JPanel DNI;
    private javax.swing.JPanel Nombre;
    private javax.swing.JSeparator SepUsuario;
    private javax.swing.JSeparator SepUsuario1;
    private javax.swing.JSeparator SepUsuario2;
    private javax.swing.JSeparator SepUsuario3;
    private javax.swing.JSeparator SepUsuario4;
    private javax.swing.JSeparator SepUsuario5;
    private javax.swing.JSeparator SepUsuario6;
    private javax.swing.JSeparator SepUsuario7;
    private javax.swing.JTextField TFAlias;
    private javax.swing.JTextField TFApellido1;
    private javax.swing.JTextField TFApellido2;
    private javax.swing.JTextField TFCurso;
    private javax.swing.JTextField TFDni;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JPanel Usuario;
    private javax.swing.JLabel al;
    private javax.swing.JLabel ap1;
    private javax.swing.JLabel ap2;
    private javax.swing.JPanel background;
    private javax.swing.JPanel buscar;
    private javax.swing.JLabel buscartxt;
    private javax.swing.JLabel cu;
    private javax.swing.JPanel curso;
    private javax.swing.JPanel datos;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel em;
    private javax.swing.JPanel email;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}
