/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author carra
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    int xMouse, yMouse;

    public MainLogin() {
        initComponents();
        Login l1 = new Login();
        l1.setSize(440, 500);
        l1.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(l1, BorderLayout.CENTER);
        Panel.revalidate();
        Panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        BarraLateral = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        AjustesBoton = new javax.swing.JPanel();
        Ajustes = new javax.swing.JLabel();
        RegisterBoton = new javax.swing.JPanel();
        RegisterTXT = new javax.swing.JLabel();
        LoginBoton = new javax.swing.JPanel();
        LoginTXT = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        xtxt = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraLateral.setBackground(new java.awt.Color(0, 155, 155));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/augusto-logo-peq.png"))); // NOI18N

        name.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Agilizando Mentes II");

        AjustesBoton.setBackground(new java.awt.Color(0, 155, 155));
        AjustesBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjustesBotonMouseClicked(evt);
            }
        });

        Ajustes.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Ajustes.setForeground(new java.awt.Color(255, 255, 255));
        Ajustes.setText("Ajustes (P)");
        Ajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout AjustesBotonLayout = new javax.swing.GroupLayout(AjustesBoton);
        AjustesBoton.setLayout(AjustesBotonLayout);
        AjustesBotonLayout.setHorizontalGroup(
            AjustesBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjustesBotonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ajustes)
                .addGap(19, 19, 19))
        );
        AjustesBotonLayout.setVerticalGroup(
            AjustesBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjustesBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ajustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegisterBoton.setBackground(new java.awt.Color(0, 155, 155));
        RegisterBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBotonMouseClicked(evt);
            }
        });

        RegisterTXT.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        RegisterTXT.setForeground(new java.awt.Color(255, 255, 255));
        RegisterTXT.setText("REGISTRO");
        RegisterTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout RegisterBotonLayout = new javax.swing.GroupLayout(RegisterBoton);
        RegisterBoton.setLayout(RegisterBotonLayout);
        RegisterBotonLayout.setHorizontalGroup(
            RegisterBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBotonLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(RegisterTXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterBotonLayout.setVerticalGroup(
            RegisterBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        LoginBoton.setBackground(new java.awt.Color(0, 155, 155));
        LoginBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBotonMouseClicked(evt);
            }
        });

        LoginTXT.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        LoginTXT.setForeground(new java.awt.Color(255, 255, 255));
        LoginTXT.setText("INICIO");
        LoginTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout LoginBotonLayout = new javax.swing.GroupLayout(LoginBoton);
        LoginBoton.setLayout(LoginBotonLayout);
        LoginBotonLayout.setHorizontalGroup(
            LoginBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBotonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LoginTXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginBotonLayout.setVerticalGroup(
            LoginBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BarraLateralLayout = new javax.swing.GroupLayout(BarraLateral);
        BarraLateral.setLayout(BarraLateralLayout);
        BarraLateralLayout.setHorizontalGroup(
            BarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLateralLayout.createSequentialGroup()
                .addGroup(BarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BarraLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(BarraLateralLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(logo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(RegisterBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AjustesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BarraLateralLayout.setVerticalGroup(
            BarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLateralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name)
                .addGap(55, 55, 55)
                .addComponent(LoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(AjustesBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        background.add(BarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 255));

        xtxt.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        xtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xtxt.setText("X");
        xtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xtxt)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 572, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        background.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 440, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void xtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xtxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xtxtMouseClicked

    private void xtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xtxtMouseEntered
        exit.setBackground(Color.red);
        xtxt.setForeground(Color.white);
    }//GEN-LAST:event_xtxtMouseEntered

    private void xtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xtxtMouseExited
        exit.setBackground(Color.white);
        xtxt.setForeground(Color.black);
    }//GEN-LAST:event_xtxtMouseExited

    private void LoginBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBotonMouseClicked
        Login l1 = new Login();
        l1.setSize(440, 500);
        l1.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(l1, BorderLayout.CENTER);
        Panel.revalidate();
        Panel.repaint();
        
    }//GEN-LAST:event_LoginBotonMouseClicked

    private void RegisterBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBotonMouseClicked
        Register R1 = new Register();
        R1.setSize(440, 500);
        R1.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(R1, BorderLayout.CENTER);
        Panel.revalidate();
        Panel.repaint();
        
    }//GEN-LAST:event_RegisterBotonMouseClicked

    private void AjustesBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjustesBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AjustesBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ajustes;
    private javax.swing.JPanel AjustesBoton;
    private javax.swing.JPanel BarraLateral;
    private javax.swing.JPanel LoginBoton;
    private javax.swing.JLabel LoginTXT;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel RegisterBoton;
    private javax.swing.JLabel RegisterTXT;
    private javax.swing.JPanel background;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel xtxt;
    // End of variables declaration//GEN-END:variables
}
