/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import Main.Main;
import java.awt.Color;
import Ajustes.*;
import BBDD.MetodosRegistroBBDD;
import java.awt.Container;

/**
 *
 * @author carra
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoRegistro = new javax.swing.JPanel();
        jPRegistro = new javax.swing.JPanel();
        registro = new javax.swing.JLabel();
        Usuario = new javax.swing.JPanel();
        us = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        SepUsuario = new javax.swing.JSeparator();
        Password = new javax.swing.JPanel();
        password = new javax.swing.JLabel();
        PWF1 = new javax.swing.JPasswordField();
        SepPassword = new javax.swing.JSeparator();
        Password2 = new javax.swing.JPanel();
        password2 = new javax.swing.JLabel();
        PWF2 = new javax.swing.JPasswordField();
        SepPassword2 = new javax.swing.JSeparator();
        Alias = new javax.swing.JPanel();
        alias = new javax.swing.JLabel();
        TFalias = new javax.swing.JTextField();
        SepAlias = new javax.swing.JSeparator();
        Nombre = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        TFnombre = new javax.swing.JTextField();
        SepNombre = new javax.swing.JSeparator();
        Apellido1 = new javax.swing.JPanel();
        apellido1 = new javax.swing.JLabel();
        TFapellido1 = new javax.swing.JTextField();
        SepApellido1 = new javax.swing.JSeparator();
        Apellido2 = new javax.swing.JPanel();
        apellido2 = new javax.swing.JLabel();
        TFapellido2 = new javax.swing.JTextField();
        SepApellido2 = new javax.swing.JSeparator();
        DNI = new javax.swing.JPanel();
        dni = new javax.swing.JLabel();
        TFdni = new javax.swing.JTextField();
        SepDni = new javax.swing.JSeparator();
        Curso = new javax.swing.JPanel();
        curso = new javax.swing.JLabel();
        TFCurso = new javax.swing.JTextField();
        SepCurso = new javax.swing.JSeparator();
        FechaNac = new javax.swing.JPanel();
        fechaNac = new javax.swing.JLabel();
        TFfechaNac = new javax.swing.JTextField();
        SepFechaNac = new javax.swing.JSeparator();
        Email = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        TFemail = new javax.swing.JTextField();
        Sepemail = new javax.swing.JSeparator();
        Registrar = new javax.swing.JPanel();
        registrar = new javax.swing.JLabel();
        profesor = new javax.swing.JRadioButton();
        inicia = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 720));

        fondoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        fondoRegistro.setPreferredSize(new java.awt.Dimension(1070, 720));
        fondoRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPRegistro.setBackground(Estilos.getColorPanel());

        registro.setFont(Estilos.getFuenteCuerpo());
        registro.setForeground(Estilos.getColorFuentePanel());
        registro.setText("Registro de nuevo usuario");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
        jPRegistro.setLayout(jPRegistroLayout);
        jPRegistroLayout.setHorizontalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPRegistroLayout.setVerticalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        fondoRegistro.add(jPRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 390, 40));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));

        us.setFont(Estilos.getFuenteCuerpo());
        us.setText("Usuario *");
        us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usMouseExited(evt);
            }
        });

        TFUsuario.setFont(Estilos.getFuenteCuerpo());
        TFUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TFUsuario.setText("Inserte su nombre de usuario");
        TFUsuario.setBorder(null);
        TFUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFUsuarioMousePressed(evt);
            }
        });
        TFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SepUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(us, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addComponent(us)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 350, 70));

        Password.setBackground(new java.awt.Color(255, 255, 255));

        password.setFont(Estilos.getFuenteCuerpo());
        password.setText("Password *");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
        });

        PWF1.setFont(Estilos.getFuenteCuerpo());
        PWF1.setForeground(new java.awt.Color(204, 204, 204));
        PWF1.setText("********");
        PWF1.setBorder(null);
        PWF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PWF1MousePressed(evt);
            }
        });
        PWF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PasswordLayout = new javax.swing.GroupLayout(Password);
        Password.setLayout(PasswordLayout);
        PasswordLayout.setHorizontalGroup(
            PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordLayout.createSequentialGroup()
                .addGroup(PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWF1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PasswordLayout.setVerticalGroup(
            PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PWF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(SepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 350, 80));

        Password2.setBackground(new java.awt.Color(255, 255, 255));

        password2.setFont(Estilos.getFuenteCuerpo());
        password2.setText("Confirmar Password *");
        password2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                password2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                password2MouseExited(evt);
            }
        });

        PWF2.setFont(Estilos.getFuenteCuerpo());
        PWF2.setForeground(new java.awt.Color(204, 204, 204));
        PWF2.setText("********");
        PWF2.setBorder(null);
        PWF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PWF2MousePressed(evt);
            }
        });

        SepPassword2.setAlignmentY(0.1F);

        javax.swing.GroupLayout Password2Layout = new javax.swing.GroupLayout(Password2);
        Password2.setLayout(Password2Layout);
        Password2Layout.setHorizontalGroup(
            Password2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PWF2)
            .addComponent(password2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(SepPassword2)
        );
        Password2Layout.setVerticalGroup(
            Password2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Password2Layout.createSequentialGroup()
                .addComponent(password2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PWF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 350, 70));

        Alias.setBackground(new java.awt.Color(255, 255, 255));

        alias.setFont(Estilos.getFuenteCuerpo());
        alias.setText("Alias");
        alias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aliasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aliasMouseExited(evt);
            }
        });

        TFalias.setFont(Estilos.getFuenteCuerpo());
        TFalias.setForeground(new java.awt.Color(204, 204, 204));
        TFalias.setText("Inserte su alias");
        TFalias.setBorder(null);
        TFalias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFaliasMousePressed(evt);
            }
        });
        TFalias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFaliasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AliasLayout = new javax.swing.GroupLayout(Alias);
        Alias.setLayout(AliasLayout);
        AliasLayout.setHorizontalGroup(
            AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SepAlias)
            .addComponent(alias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TFalias, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        AliasLayout.setVerticalGroup(
            AliasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AliasLayout.createSequentialGroup()
                .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFalias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 350, 70));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));

        nombre.setFont(Estilos.getFuenteCuerpo());
        nombre.setText("Nombre *");
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombreMouseExited(evt);
            }
        });

        TFnombre.setFont(Estilos.getFuenteCuerpo());
        TFnombre.setForeground(new java.awt.Color(204, 204, 204));
        TFnombre.setText("Inserte su nombre");
        TFnombre.setBorder(null);
        TFnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFnombreMousePressed(evt);
            }
        });
        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreLayout = new javax.swing.GroupLayout(Nombre);
        Nombre.setLayout(NombreLayout);
        NombreLayout.setHorizontalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TFnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(SepNombre, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        NombreLayout.setVerticalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(SepNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoRegistro.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 350, 70));

        Apellido1.setBackground(new java.awt.Color(255, 255, 255));

        apellido1.setFont(Estilos.getFuenteCuerpo());
        apellido1.setText("Primer apellido*");
        apellido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apellido1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apellido1MouseExited(evt);
            }
        });

        TFapellido1.setFont(Estilos.getFuenteCuerpo());
        TFapellido1.setForeground(new java.awt.Color(204, 204, 204));
        TFapellido1.setText("Inserte su primer apellido");
        TFapellido1.setBorder(null);
        TFapellido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFapellido1MousePressed(evt);
            }
        });
        TFapellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFapellido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Apellido1Layout = new javax.swing.GroupLayout(Apellido1);
        Apellido1.setLayout(Apellido1Layout);
        Apellido1Layout.setHorizontalGroup(
            Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TFapellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(SepApellido1)
        );
        Apellido1Layout.setVerticalGroup(
            Apellido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido1Layout.createSequentialGroup()
                .addComponent(apellido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(SepApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoRegistro.add(Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 350, 70));

        Apellido2.setBackground(new java.awt.Color(255, 255, 255));

        apellido2.setFont(Estilos.getFuenteCuerpo());
        apellido2.setText("Segundo apellido");
        apellido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apellido2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apellido2MouseExited(evt);
            }
        });

        TFapellido2.setFont(Estilos.getFuenteCuerpo());
        TFapellido2.setForeground(new java.awt.Color(204, 204, 204));
        TFapellido2.setText("Inserte su segundo apellido");
        TFapellido2.setBorder(null);
        TFapellido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFapellido2MousePressed(evt);
            }
        });
        TFapellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFapellido2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Apellido2Layout = new javax.swing.GroupLayout(Apellido2);
        Apellido2.setLayout(Apellido2Layout);
        Apellido2Layout.setHorizontalGroup(
            Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido2Layout.createSequentialGroup()
                .addGroup(Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SepApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Apellido2Layout.setVerticalGroup(
            Apellido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Apellido2Layout.createSequentialGroup()
                .addComponent(apellido2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 350, 70));

        DNI.setBackground(new java.awt.Color(255, 255, 255));

        dni.setFont(Estilos.getFuenteCuerpo());
        dni.setText("DNI *");
        dni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dniMouseExited(evt);
            }
        });

        TFdni.setFont(Estilos.getFuenteCuerpo());
        TFdni.setForeground(new java.awt.Color(204, 204, 204));
        TFdni.setText("Inserte su DNI");
        TFdni.setBorder(null);
        TFdni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFdniMousePressed(evt);
            }
        });
        TFdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DNILayout = new javax.swing.GroupLayout(DNI);
        DNI.setLayout(DNILayout);
        DNILayout.setHorizontalGroup(
            DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SepDni)
            .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TFdni, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        DNILayout.setVerticalGroup(
            DNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DNILayout.createSequentialGroup()
                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 350, 70));

        Curso.setBackground(new java.awt.Color(255, 255, 255));

        curso.setFont(Estilos.getFuenteCuerpo());
        curso.setText("Curso *");
        curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cursoMouseExited(evt);
            }
        });

        TFCurso.setFont(Estilos.getFuenteCuerpo());
        TFCurso.setForeground(new java.awt.Color(204, 204, 204));
        TFCurso.setText("Inserte su curso");
        TFCurso.setBorder(null);
        TFCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFCursoMousePressed(evt);
            }
        });
        TFCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CursoLayout = new javax.swing.GroupLayout(Curso);
        Curso.setLayout(CursoLayout);
        CursoLayout.setHorizontalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursoLayout.createSequentialGroup()
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TFCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(curso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SepCurso, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CursoLayout.setVerticalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursoLayout.createSequentialGroup()
                .addComponent(curso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 350, 70));

        FechaNac.setBackground(new java.awt.Color(255, 255, 255));

        fechaNac.setFont(Estilos.getFuenteCuerpo());
        fechaNac.setText("Fecha de Nacimiento *");
        fechaNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechaNacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechaNacMouseExited(evt);
            }
        });

        TFfechaNac.setFont(Estilos.getFuenteCuerpo());
        TFfechaNac.setForeground(new java.awt.Color(204, 204, 204));
        TFfechaNac.setText("yyyy-mm-dd");
        TFfechaNac.setBorder(null);
        TFfechaNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFfechaNacMousePressed(evt);
            }
        });
        TFfechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFfechaNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FechaNacLayout = new javax.swing.GroupLayout(FechaNac);
        FechaNac.setLayout(FechaNacLayout);
        FechaNacLayout.setHorizontalGroup(
            FechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FechaNacLayout.createSequentialGroup()
                .addGroup(FechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SepFechaNac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFfechaNac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FechaNacLayout.setVerticalGroup(
            FechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FechaNacLayout.createSequentialGroup()
                .addComponent(fechaNac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFfechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SepFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(FechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, 70));

        Email.setBackground(new java.awt.Color(255, 255, 255));

        email.setFont(Estilos.getFuenteCuerpo());
        email.setText("Email *");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });

        TFemail.setFont(Estilos.getFuenteCuerpo());
        TFemail.setForeground(new java.awt.Color(204, 204, 204));
        TFemail.setText("ejemplo@ejemplo.com");
        TFemail.setBorder(null);
        TFemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFemailMousePressed(evt);
            }
        });
        TFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmailLayout = new javax.swing.GroupLayout(Email);
        Email.setLayout(EmailLayout);
        EmailLayout.setHorizontalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TFemail, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(Sepemail)
        );
        EmailLayout.setVerticalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Sepemail, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegistro.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 350, 70));

        Registrar.setBackground(Estilos.getColorPanel());
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
        });

        registrar.setFont(Estilos.getFuenteCuerpo());
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar.setText("REGISTRAR");

        javax.swing.GroupLayout RegistrarLayout = new javax.swing.GroupLayout(Registrar);
        Registrar.setLayout(RegistrarLayout);
        RegistrarLayout.setHorizontalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        RegistrarLayout.setVerticalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoRegistro.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 190, 50));

        profesor.setFont(Estilos.getFuenteCuerpo());
        profesor.setText("Soy Profesor");
        profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profesorMouseExited(evt);
            }
        });
        fondoRegistro.add(profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 180, 30));

        inicia.setFont(Estilos.getFuenteCuerpo());
        inicia.setForeground(new java.awt.Color(0, 153, 255));
        inicia.setText("Inicia sesión aquí.");
        inicia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inicia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iniciaMousePressed(evt);
            }
        });
        fondoRegistro.add(inicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciaMouseEntered
        inicia.setFont(Estilos.getFuenteCuerpo());
           if (Configuracion.isSonido()) {
            Configuracion.sonar("inicia_sesion");
        }
        
    }//GEN-LAST:event_iniciaMouseEntered

    private void PWF1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PWF1MousePressed
        if (String.valueOf(PWF1.getPassword()).equals("********")) {
            PWF1.setText("");
            PWF1.setForeground(Color.black);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.black);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido1.getText().isEmpty()) {
            TFapellido1.setText("Inserte su primer apellido");
            TFapellido1.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }

    }//GEN-LAST:event_PWF1MousePressed

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        boolean register = true;
        //COMPRUEBO QUE EL USUARIO A INTRODUCIDO TODO LO QUE TIENE QUE INTRODUCIR

        //COMPRUEBO EL USUARIO
        if (!(TFUsuario.getText().isEmpty() || TFUsuario.getText().equals("Inserte su nombre de usuario"))) {
            if (MetodosRegistroBBDD.comprobarNombreUsuario(Main.getCon(), TFUsuario.getText())) {
                us.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                us.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            us.setForeground(Estilos.getColorFuenteError());
        }

        //COMPRUEBO LA PRIMERA CONTRASEÑA
        if (String.valueOf(PWF1.getPassword()).isEmpty() || String.valueOf(PWF1.getPassword()).equals("********")) {
            password.setForeground(Estilos.getColorFuenteError());
            register = false;
        } else {
            password.setForeground(Estilos.getColorFuenteCuerpo());
            register = true;
        }

        //COMPRUEBO LA VALIDACION DE LA CONTRASEÑA
        if (!(String.valueOf(PWF2.getPassword()).isEmpty() || String.valueOf(PWF2.getPassword()).equals("********"))) {
            if (!String.valueOf(PWF2.getPassword()).equals(String.valueOf(PWF1.getPassword()))) {
                password2.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                password2.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            password2.setForeground(Estilos.getColorFuenteError());
            register = false;
        }

        //COMPRUEBO EL ALIAS
        if (!TFalias.getText().equals("Inserte su alias")) {
            if (MetodosRegistroBBDD.comprobrarAlias(Main.getCon(), TFalias.getText())) {
                alias.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                alias.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }
        } else {
            if (!(TFUsuario.getText().isEmpty() || TFUsuario.getText().equals("Inserte su nombre de usuario"))) {
                if (MetodosRegistroBBDD.comprobrarAlias(Main.getCon(), TFUsuario.getText())) {
                    alias.setForeground(Estilos.getColorFuenteError());
                    register = false;
                } else {
                    alias.setForeground(Estilos.getColorFuenteCuerpo());
                    register = true;
                }
            } else {
                alias.setForeground(Estilos.getColorFuenteError());
                register = false;
            }

        }

        //COMPRUEBO EL NOMBRE
        if (TFnombre.getText().isEmpty() || TFnombre.getText().equals("Inserte su nombre")) {
            nombre.setForeground(Estilos.getColorFuenteError());
            register = false;
        } else {
            nombre.setForeground(Estilos.getColorFuenteCuerpo());
            register = true;
        }

        //COMPRUEBO EL APELLIDO 1
        if (TFapellido1.getText().isEmpty() || TFapellido1.getText().equals("Inserte su primer apellido")) {
            apellido1.setForeground(Estilos.getColorFuenteError());
            register = false;
        } else {
            apellido1.setForeground(Estilos.getColorFuenteCuerpo());
            register = true;
        }

        //COMPRUEBO EL DNI
        if (!(TFdni.getText().isEmpty() || TFdni.getText().equals("Inserte su DNI"))) {
            if (!MetodosRegistroBBDD.comprobarDNI(Main.getCon(), TFdni.getText())) {
                dni.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                dni.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            dni.setForeground(Estilos.getColorFuenteError());
            register = false;
        }

        //COMPRUEBO EL CURSO
        if (!(TFCurso.getText().isEmpty() || TFCurso.getText().equals("Inserte su curso"))) {
            if (!MetodosRegistroBBDD.comprobarCurso(TFCurso.getText())) {
                curso.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                curso.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            curso.setForeground(Estilos.getColorFuenteError());
            register = false;
        }

        //COMPRUEBO LA FECHA
        if (!(TFfechaNac.getText().isEmpty() || TFfechaNac.getText().equals("yyyy-mm-dd"))) {
            if (!MetodosRegistroBBDD.comprobarFecha(TFfechaNac.getText())) {
                fechaNac.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                fechaNac.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            fechaNac.setForeground(Estilos.getColorFuenteError());
            register = false;
        }

        //COMPRUEBO EL EMAIL
        if (!(TFemail.getText().isEmpty() || TFemail.getText().equals("ejemplo@ejemplo.com"))) {
            if (MetodosRegistroBBDD.comprobrarEmail(Main.getCon(), TFemail.getText())) {
                email.setForeground(Estilos.getColorFuenteError());
                register = false;
            } else {
                email.setForeground(Estilos.getColorFuenteCuerpo());
                register = true;
            }

        } else {
            email.setForeground(Estilos.getColorFuenteError());
            register = false;
        }

        //SI EL USUARIO A INTRODUCCIDO BIEN LOS DATOS REGISTRO AL USUARIO
        if (register) {
            if (TFalias.getText().equals("Inserte su alias")) {
                TFalias.setText(TFUsuario.getText());
            }
            if (TFapellido2.getText().equals("Inserte su segundo apellido")) {
                TFapellido2.setText("");
            }
            if (profesor.isSelected()) {
                TFCurso.setText("5");
            }
            MetodosRegistroBBDD.registrarUsuario(Main.getCon(), TFUsuario.getText(), String.valueOf(PWF1.getPassword()), TFalias.getText(), TFnombre.getText(), TFapellido1.getText(), TFapellido2.getText(), TFdni.getText(), Integer.parseInt(TFCurso.getText()), TFfechaNac.getText(), TFemail.getText(), profesor.isSelected());

            Container Cuerpo2 = this.getParent();
            Login l1 = new Login();
            l1.setSize(1070, 720);
            l1.setLocation(0, 0);
            Cuerpo2.removeAll();
            Cuerpo2.add(l1);
            Cuerpo2.revalidate();
            Cuerpo2.repaint();

        }

    }//GEN-LAST:event_RegistrarMouseClicked

    private void RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseEntered
        Registrar.setBackground(Estilos.getColorSobreBoton());
        if (Configuracion.isSonido()) {
            Configuracion.sonar("registrar");
        }
    }//GEN-LAST:event_RegistrarMouseEntered

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        Registrar.setBackground(Estilos.getColorPanel());
        Configuracion.parar();
    }//GEN-LAST:event_RegistrarMouseExited

    private void TFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUsuarioActionPerformed

    private void TFUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUsuarioMousePressed
        if (TFUsuario.getText().equals("Inserte su nombre de usuario")) {
            TFUsuario.setText("");
            TFUsuario.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido1.getText().isEmpty()) {
            TFapellido1.setText("Inserte su primer apellido");
            TFapellido1.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFUsuarioMousePressed

    private void TFapellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFapellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFapellido2ActionPerformed

    private void TFapellido2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFapellido2MousePressed
        if (TFapellido2.getText().equals("Inserte su segundo apellido")) {
            TFapellido2.setText("");
            TFapellido2.setForeground(Color.gray);
        }

        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido1.getText().isEmpty()) {
            TFapellido1.setText("Inserte su primer apellido");
            TFapellido1.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFapellido2MousePressed

    private void TFapellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFapellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFapellido1ActionPerformed

    private void TFapellido1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFapellido1MousePressed
        if (TFapellido1.getText().equals("Inserte su primer apellido")) {
            TFapellido1.setText("");
            TFapellido1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFapellido1MousePressed

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnombreActionPerformed

    private void TFnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFnombreMousePressed
        if (TFnombre.getText().equals("Inserte su nombre")) {
            TFnombre.setText("");
            TFnombre.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFnombreMousePressed

    private void TFfechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFfechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFfechaNacActionPerformed

    private void TFfechaNacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFfechaNacMousePressed
        if (TFfechaNac.getText().equals("yyyy-mm-dd")) {
            TFfechaNac.setText("");
            TFfechaNac.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFfechaNacMousePressed

    private void TFCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCursoActionPerformed

    private void TFCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFCursoMousePressed
        if (TFCurso.getText().equals("Inserte su curso")) {
            TFCurso.setText("");
            TFCurso.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFCursoMousePressed

    private void TFdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdniActionPerformed

    private void TFdniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFdniMousePressed
        if (TFdni.getText().equals("Inserte su DNI")) {
            TFdni.setText("");
            TFdni.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFdniMousePressed

    private void TFaliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFaliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFaliasActionPerformed

    private void TFaliasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFaliasMousePressed
        if (TFalias.getText().equals("Inserte su alias")) {
            TFalias.setText("");
            TFalias.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFaliasMousePressed

    private void iniciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciaMousePressed
        Container Cuerpo2 = this.getParent();
        Login l1 = new Login();
        l1.setSize(1070, 720);
        l1.setLocation(0, 0);
        Cuerpo2.removeAll();
        Cuerpo2.add(l1);
        Cuerpo2.revalidate();
        Cuerpo2.repaint();
    }//GEN-LAST:event_iniciaMousePressed

    private void TFemailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFemailMousePressed
        if (TFemail.getText().equals("ejemplo@ejemplo.com")) {
            TFemail.setText("");
            TFemail.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (String.valueOf(PWF2.getPassword()).isEmpty()) {
            PWF2.setText("********");
            PWF2.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFemailMousePressed

    private void TFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFemailActionPerformed

    private void PWF2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PWF2MousePressed
        if (String.valueOf(PWF2.getPassword()).equals("********")) {
            PWF2.setText("");
            PWF2.setForeground(Color.gray);
        }
        if (String.valueOf(PWF1.getPassword()).isEmpty()) {
            PWF1.setText("********");
            PWF1.setForeground(Color.gray);
        }
        if (TFUsuario.getText().isEmpty()) {
            TFUsuario.setText("Inserte su nombre de usuario");
            TFUsuario.setForeground(Color.gray);
        }
        if (TFalias.getText().isEmpty()) {
            TFalias.setText("Inserte su alias");
            TFalias.setForeground(Color.gray);
        }
        if (TFnombre.getText().isEmpty()) {
            TFnombre.setText("Inserte su nombre");
            TFnombre.setForeground(Color.gray);
        }
        if (TFapellido1.getText().isEmpty()) {
            TFapellido1.setText("Inserte su primer apellido");
            TFapellido1.setForeground(Color.gray);
        }
        if (TFapellido2.getText().isEmpty()) {
            TFapellido2.setText("Inserte su segundo apellido");
            TFapellido2.setForeground(Color.gray);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("Inserte su DNI");
            TFdni.setForeground(Color.gray);
        }
        if (TFCurso.getText().isEmpty()) {
            TFCurso.setText("Inserte su curso");
            TFCurso.setForeground(Color.gray);
        }
        if (TFfechaNac.getText().isEmpty()) {
            TFfechaNac.setText("yyyy-mm-dd");
            TFfechaNac.setForeground(Color.gray);
        }
        if (TFemail.getText().isEmpty()) {
            TFemail.setText("ejemplo@ejemplo.com");
            TFemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PWF2MousePressed

    private void registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseEntered
        if (Configuracion.isSonido()) {
            Configuracion.sonar("registro_nuevo");
        }
    }//GEN-LAST:event_registroMouseEntered

    private void registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_registroMouseExited

    private void usMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("usuario");
        }
    }//GEN-LAST:event_usMouseEntered

    private void usMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_usMouseExited

    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("contrasena");
        }
    }//GEN-LAST:event_passwordMouseEntered

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_passwordMouseExited

    private void password2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password2MouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("contrasena");
        }
    }//GEN-LAST:event_password2MouseEntered

    private void password2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password2MouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_password2MouseExited

    private void aliasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aliasMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("alias");
        }
    }//GEN-LAST:event_aliasMouseEntered

    private void aliasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aliasMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_aliasMouseExited

    private void nombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("nombre");
        }
    }//GEN-LAST:event_nombreMouseEntered

    private void nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_nombreMouseExited

    private void apellido1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido1MouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("apellido1");
        }
    }//GEN-LAST:event_apellido1MouseEntered

    private void apellido1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido1MouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_apellido1MouseExited

    private void apellido2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido2MouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("apellido2");
        }
    }//GEN-LAST:event_apellido2MouseEntered

    private void apellido2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido2MouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_apellido2MouseExited

    private void dniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("dni");
        }
    }//GEN-LAST:event_dniMouseEntered

    private void dniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_dniMouseExited

    private void cursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("curso");
        }
    }//GEN-LAST:event_cursoMouseEntered

    private void cursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_cursoMouseExited

    private void fechaNacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaNacMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("fecha");
        }
    }//GEN-LAST:event_fechaNacMouseEntered

    private void fechaNacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaNacMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_fechaNacMouseExited

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("email");
        }
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_emailMouseExited

    private void profesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesorMouseEntered
        // TODO add your handling code here:
        if (Configuracion.isSonido()) {
            Configuracion.sonar("profesor");
        }
    }//GEN-LAST:event_profesorMouseEntered

    private void profesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesorMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_profesorMouseExited

    private void iniciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciaMouseExited
        // TODO add your handling code here:
        Configuracion.parar();
    }//GEN-LAST:event_iniciaMouseExited

    private void PWF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PWF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alias;
    private javax.swing.JPanel Apellido1;
    private javax.swing.JPanel Apellido2;
    private javax.swing.JPanel Curso;
    private javax.swing.JPanel DNI;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel FechaNac;
    private javax.swing.JPanel Nombre;
    private javax.swing.JPasswordField PWF1;
    private javax.swing.JPasswordField PWF2;
    private javax.swing.JPanel Password;
    private javax.swing.JPanel Password2;
    private javax.swing.JPanel Registrar;
    private javax.swing.JSeparator SepAlias;
    private javax.swing.JSeparator SepApellido1;
    private javax.swing.JSeparator SepApellido2;
    private javax.swing.JSeparator SepCurso;
    private javax.swing.JSeparator SepDni;
    private javax.swing.JSeparator SepFechaNac;
    private javax.swing.JSeparator SepNombre;
    private javax.swing.JSeparator SepPassword;
    private javax.swing.JSeparator SepPassword2;
    private javax.swing.JSeparator SepUsuario;
    private javax.swing.JSeparator Sepemail;
    private javax.swing.JTextField TFCurso;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JTextField TFalias;
    private javax.swing.JTextField TFapellido1;
    private javax.swing.JTextField TFapellido2;
    private javax.swing.JTextField TFdni;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFfechaNac;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JPanel Usuario;
    private javax.swing.JLabel alias;
    private javax.swing.JLabel apellido1;
    private javax.swing.JLabel apellido2;
    private javax.swing.JLabel curso;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fechaNac;
    private javax.swing.JPanel fondoRegistro;
    private javax.swing.JLabel inicia;
    private javax.swing.JPanel jPRegistro;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password2;
    private javax.swing.JRadioButton profesor;
    private javax.swing.JLabel registrar;
    private javax.swing.JLabel registro;
    private javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}
