/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Alumno;

import Usuario.Usuario;
import Ajustes.*;


/**
 *
 * @author damt111
 */
public class BienvenidaA extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public BienvenidaA() {
        initComponents();
        alias.setText(Usuario.getAlias());
        nombre.setText(Usuario.getNombre());
        Apellido.setText(Usuario.getApellido1() +" "+Usuario.getApellido2() );

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        alias = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        bienvenido1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(Estilos.getFuenteCuerpo());
        bienvenido.setForeground(Estilos.getColorFuenteCuerpo());
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("Selecciona una actividad en el menú de la izquierda.");
        jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 660, 30));

        alias.setFont(Estilos.getFuenteCuerpo());
        alias.setForeground(Estilos.getColorFuenteCuerpo());
        alias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alias.setText("Alias");
        jPanel1.add(alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 720, 30));

        nombre.setFont(Estilos.getFuenteCuerpo());
        nombre.setForeground(Estilos.getColorFuenteCuerpo());
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 580, 30));

        Apellido.setFont(Estilos.getFuenteCuerpo());
        Apellido.setForeground(Estilos.getColorFuenteCuerpo());
        Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apellido.setText("Apellido");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 580, 30));

        bienvenido1.setFont(Estilos.getFuenteCuerpo());
        bienvenido1.setForeground(Estilos.getColorFuenteCuerpo());
        bienvenido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido1.setText("Bienvenido a Agilizando Mentes II");
        jPanel1.add(bienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel alias;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel bienvenido1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
