/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Alumno;

import Ajustes.*;
import Calculadora.Calculadora;
import Euclides.Euclides;
import java.awt.Container;
import Main.*;
import RestoDiv.RestoDiv;

/**
 *
 * @author damt111
 */
public class PanelAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlumno
     */
    public PanelAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAlumnos = new javax.swing.JPanel();
        Cálculo = new javax.swing.JPanel();
        LoginTXT4 = new javax.swing.JLabel();
        Euclides1 = new javax.swing.JPanel();
        Euclides = new javax.swing.JLabel();
        RestoDivision = new javax.swing.JPanel();
        LoginTXT = new javax.swing.JLabel();
        Calculadora = new javax.swing.JPanel();
        LoginTXT3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(210, 330));
        setRequestFocusEnabled(false);

        PanelAlumnos.setBackground(new java.awt.Color(0, 155, 155));
        PanelAlumnos.setPreferredSize(new java.awt.Dimension(210, 330));

        Cálculo.setBackground(new java.awt.Color(0, 155, 155));
        Cálculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cálculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CálculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CálculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CálculoMouseExited(evt);
            }
        });

        LoginTXT4.setFont(Estilos.getFuentePanel());
        LoginTXT4.setForeground(new java.awt.Color(255, 255, 255));
        LoginTXT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTXT4.setText("Cálculo");
        LoginTXT4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout CálculoLayout = new javax.swing.GroupLayout(Cálculo);
        Cálculo.setLayout(CálculoLayout);
        CálculoLayout.setHorizontalGroup(
            CálculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTXT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CálculoLayout.setVerticalGroup(
            CálculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTXT4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        Euclides1.setBackground(new java.awt.Color(0, 155, 155));
        Euclides1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Euclides1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Euclides1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Euclides1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Euclides1MouseExited(evt);
            }
        });

        Euclides.setFont(Estilos.getFuentePanel());
        Euclides.setForeground(new java.awt.Color(255, 255, 255));
        Euclides.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Euclides.setText("Euclides");
        Euclides.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Euclides1Layout = new javax.swing.GroupLayout(Euclides1);
        Euclides1.setLayout(Euclides1Layout);
        Euclides1Layout.setHorizontalGroup(
            Euclides1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Euclides, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Euclides1Layout.setVerticalGroup(
            Euclides1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Euclides, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        RestoDivision.setBackground(new java.awt.Color(0, 155, 155));
        RestoDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestoDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestoDivisionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestoDivisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestoDivisionMouseExited(evt);
            }
        });

        LoginTXT.setFont(Estilos.getFuentePanel());
        LoginTXT.setForeground(new java.awt.Color(255, 255, 255));
        LoginTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTXT.setText("Resto división");
        LoginTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout RestoDivisionLayout = new javax.swing.GroupLayout(RestoDivision);
        RestoDivision.setLayout(RestoDivisionLayout);
        RestoDivisionLayout.setHorizontalGroup(
            RestoDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        RestoDivisionLayout.setVerticalGroup(
            RestoDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        Calculadora.setBackground(new java.awt.Color(0, 155, 155));
        Calculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculadoraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CalculadoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalculadoraMouseExited(evt);
            }
        });

        LoginTXT3.setFont(Estilos.getFuentePanel());
        LoginTXT3.setForeground(new java.awt.Color(255, 255, 255));
        LoginTXT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTXT3.setText("Calculadora ");
        LoginTXT3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout CalculadoraLayout = new javax.swing.GroupLayout(Calculadora);
        Calculadora.setLayout(CalculadoraLayout);
        CalculadoraLayout.setHorizontalGroup(
            CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTXT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CalculadoraLayout.setVerticalGroup(
            CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculadoraLayout.createSequentialGroup()
                .addComponent(LoginTXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAlumnosLayout = new javax.swing.GroupLayout(PanelAlumnos);
        PanelAlumnos.setLayout(PanelAlumnosLayout);
        PanelAlumnosLayout.setHorizontalGroup(
            PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addComponent(Calculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Cálculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Euclides1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RestoDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelAlumnosLayout.setVerticalGroup(
            PanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Cálculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RestoDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Euclides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Calculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CálculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CálculoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CálculoMouseClicked

    private void Euclides1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Euclides1MouseClicked
        // TODO add your handling code here:
        Euclides panel = new Euclides();
        panel.setSize(1070, 720);
        panel.setLocation(0, 0);
        Main.getCuerpo().removeAll();
        Main.getCuerpo().add(panel);
        Main.getCuerpo().revalidate();
        Main.getCuerpo().repaint();
    }//GEN-LAST:event_Euclides1MouseClicked

    private void RestoDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoDivisionMouseClicked
        // TODO add your handling code here:
        RestoDiv panel = new RestoDiv();
        panel.setSize(1070, 720);
        panel.setLocation(0, 0);
        Main.getCuerpo().removeAll();
        Main.getCuerpo().add(panel);
        Main.getCuerpo().revalidate();
        Main.getCuerpo().repaint();
    }//GEN-LAST:event_RestoDivisionMouseClicked

    private void CalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculadoraMouseClicked
        Calculadora calcu = new Calculadora();
        calcu.setVisible(true);
    }//GEN-LAST:event_CalculadoraMouseClicked

    private void CálculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CálculoMouseEntered
        Cálculo.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_CálculoMouseEntered

    private void CálculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CálculoMouseExited
        Cálculo.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_CálculoMouseExited

    private void RestoDivisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoDivisionMouseEntered
        RestoDivision.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_RestoDivisionMouseEntered

    private void RestoDivisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoDivisionMouseExited
       RestoDivision.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_RestoDivisionMouseExited

    private void Euclides1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Euclides1MouseEntered
        Euclides1.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_Euclides1MouseEntered

    private void Euclides1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Euclides1MouseExited
        Euclides1.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_Euclides1MouseExited

    private void CalculadoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculadoraMouseEntered
         Calculadora.setBackground(Estilos.getColorSobreBoton());
    }//GEN-LAST:event_CalculadoraMouseEntered

    private void CalculadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculadoraMouseExited
        Calculadora.setBackground(Estilos.getColorPanel());
    }//GEN-LAST:event_CalculadoraMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calculadora;
    private javax.swing.JPanel Cálculo;
    private javax.swing.JLabel Euclides;
    private javax.swing.JPanel Euclides1;
    private javax.swing.JLabel LoginTXT;
    private javax.swing.JLabel LoginTXT3;
    private javax.swing.JLabel LoginTXT4;
    private javax.swing.JPanel PanelAlumnos;
    private javax.swing.JPanel RestoDivision;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
